// # Copyright (c) ZStack.io, Inc.

package test

import (
	"testing"

	"github.com/kataras/golog"

	"dev.zstack.io/ye.zou/zstack-go-sdk/pkg/param"
)

func TestQueryAccessKeys(t *testing.T) {
	queryParam := param.NewQueryParam()
	accessKeys, err := accountLoginCli.QueryAccessKey(&queryParam)
	if err != nil {
		t.Errorf("TestQueryAccessKeys err %v", err)
		return
	}
	golog.Infof("Query access keys result: %v", accessKeys)
}

func TestCreateGetDeleteAccessKeyFlow(t *testing.T) {
	// Ensure we have a logged-in client and obtain account & user UUIDs
	// Uses the global loginSession from TestMain in base_actions_test.go
	if loginSession == nil {
		t.Fatalf("Login session is nil, TestMain failed to login or was not run")
	}
	sess := loginSession

	// Let ZStack auto-generate the AccessKeyID and AccessKeySecret
	createParam := param.CreateAccessKeyParam{
		BaseParam: param.BaseParam{},
		Params: param.CreateAccessKeyParamDetail{
			AccountUuid: sess.AccountUuid,
			UserUuid:    sess.UserUuid,
			Description: nil,
			// AccessKeyID and AccessKeySecret will be auto-generated by ZStack when nil
		},
	}

	// Create the access key
	resp, err := accountLoginCli.CreateAccessKey(createParam)
	if err != nil {
		t.Fatalf("CreateAccessKey error: %v", err)
	}
	if resp == nil {
		t.Fatalf("CreateAccessKey returned nil response")
	}
	golog.Infof("Created access key: %v", resp)

	// Try to get the access key by UUID
	/*
		getResp, err := accountLoginCli.GetAccessKey(resp.UUID)
		if err != nil {
			t.Fatalf("GetAccessKey error: %v", err)
		}
		golog.Infof("Get access key: %v", getResp)

		// Delete the access key
		err = accountLoginCli.DeleteAccessKey(resp.UUID, param.DeleteModePermissive)
		if err != nil {
			t.Errorf("DeleteAccessKey error: %v", err)
			// don't return right away; we may still want to check deletion or proceed to cleanup in other tests
		}
	*/

	// Optionally verify that querying with the accessKeyID returns none or not; skipping strict assertion for environment variance
}
